### PR TITLE
fix(regnet): fix lotka volterra model to have the correct equations

### PR DESCRIPTION
**Pull request by mehalter**
Also I have run the validation locally and promise this passes. Currently GitHub is on a like 9 hour streak of constant issues with GitHub Actions (githubstatus.com)

2023-05-10_18:20:50_screenshot

### CODE REVIEW

**Comment by bgyori** [comment]
Hi @mehalter, this issue came up in the TA2 meeting today. I think the consensus was to 
(1) Keep this model (since it exercises several different features of regnets that a plain LV model would not) but just give it a different file name.
(2) Add the model @djinnome wrote up in this comment: https://github.com/DARPA-ASKEM/Model-Representations/issues/11#issuecomment-1539048298 as the canonical LV model as an example.
Does this make sense?

**Comment by mehalter** [comment]
Yup @bgyori ! I can update this PR to save the old file as a different example. The changes I made to the file currently actually do reflect the comment you have linked as well. I can make sure the descriptions and things line up.

**Comment by mehalter** [comment]
@bgyori I have updated the PR to save the old model as another example along with the fixed Lotka Volterra model

**Review by bgyori — APPROVED** [review]
Looks good to me now, thanks!

**Pull request merged**
