### PR TITLE
Regulatory Network model representation JSON schema

### LINKED ISSUE #11: RegNets Schema Discussion
I started taking a look at making a JSON format for RegNets. This takes some ideas from our already existing Petri Net schema such as grounding and how we represent rates/initial conditions and applies them to the idea of signed graphs. This is to be a starting point for our discussion in the coming week for formalizing a JSON Schema.

We can use this issue to forward the development before the meeting and bring up missing information/fields.

```json
{
  "name": "Lotka Volterra",
  "schema": "TODO",
  "description": "Lotka Volterra model",
  "model_version": "0.1",
  "model": {
    "vertices": [
      {
        "id": "R",
        "name": "Rabbits",
        "grounding": {},
        "initial": {
          "expression": "R0",
          "expression_mathml": "<mi>R0</mi>"
        }
      },
      {
        "id": "W",
        "name": "Wolves",
        "grounding": {},
        "initial": {
          "expression": "W0",
          "expression_mathml": "<mi>W0</mi>"
        }
      }
    ],
    "edges": [
      {
        "id": "rabbit_growth",
        "src": "R",
        "tgt": "R",
        "sign": true,
        "properties": {
          "name": "",
          "rate": {
            "expression": "",
            "expression_mathml": ""
          }
        }
      },
      {
        "id": "wolf_growth",
        "src": "W",
        "tgt": "W",
        "sign": true,
        "properties": {
          "name": "",
          "rate": {
            "expression": "",
            "expression_mathml": ""
          }
        }
      },
      {
        "id": "predation",
        "src": "W",
        "tgt": "R",
        "sign": false,
        "properties": {
          "name": "",
          "function": {
            "expression": "",
            "expression_mathml": ""
          }
        }
      }
    ],
    "parameters": [
      {
        "id": "R0",
        "description": "Initial rabbit population",
        "value": 10
      },
      {
        "id": "W0",
        "description": "Initial wolf population",
        "value": 1
      }
    ]
  }
}
```

Pinging @bgyori @brandomr specifically to get eyes on this and for feedback!

I think the only thing that may be missing is currently missing is intrinsic growth rates on the vertices themselves, @jpfairbanks could you weigh in on how we should add that in along with the initial conditions. I'm also not 100% clear as to why intrinsic growth rates are needed and why they aren't positive edges in the regulatory network.

### PR DESCRIPTION
**Pull request by mehalter**
This implements the JSON schema validation for our new regulatory network JSON schema.

Resolves #11

### CODE REVIEW

**Comment by mehalter** [comment]
@brandomr @bgyori @jpfairbanks what do you think of this? Still needs a README with some details of the semantics it encodes

**Comment by brandomr** [comment]
This seems great to me. We could enhance the example to use distributions over the parameters and to include metadata extractions, but those seem like "bonus points" to me.

I think any issues around the edges will come out during the stress test later this week so feel like this is good enough to move forward with unless others have strong feelings about things that should be addressed prior to Thursday.

**Comment by bgyori** [comment]
Yes, that's right. Sure, we can merge it as is for now.

**Review by brandomr — APPROVED** [review]

**Comment by jpfairbanks** [comment]
Micah and I just talked over this format as merged. Since we don't want to reopen the discussion, I'm just documenting our interpretation and how it might differ from other implementations.

There are signs _and_ rates on the vertices _and_ edges. In our internal representation we are going to store the vertices without signs but with Float64 rates, and store edges with signs and nonnegative rates. When reading a model:

1. We will throw an exception if we get an edge rate < 0. 
2. We will accept a negative vertex rate and multiply it by the vertex sign.

When writing a model, we will emit positive vertex rates and set the sign as the sign of the internally stored rate.

That is a little inconsistent, but is the easiest thing to do to compromise with the merged framework. If all the vertex and edge rates are positive, then I think we get the unambiguously correct behavior, but when the vertex or edge rates are negative, then the correct behavior is ambiguous. 

We don't have time to relitigate anything in this spec, so I'm just documenting our interpretation. Other implementations should take a similar interpretation, but can do their own thing if they want.

**Pull request merged**
