### PR TITLE
Add simple node validation script

### PR DESCRIPTION
**Pull request by mattprintz**
Validates all examples against the schema definitions.

### CODE REVIEW

**Comment by bgyori** [comment]
I think this is partially redundant with the validation workflow implemented in https://github.com/DARPA-ASKEM/Model-Representations/pull/1. I do think it's a good idea to not only test the examples but also the individual schemas with respect to the base schema, but perhaps should we do that as an extension to https://github.com/DARPA-ASKEM/Model-Representations/pull/1 for consistency?

**Comment by mehalter** [comment]
I'm gonna take a look at this a bit more over the next couple days. I think this does a really good job at validating things and maybe we can replace our GitHub action as well with this. The benefit having this provides is a way to validate things locally which greatly improves local development

**Comment by bgyori** [comment]
If we are going with this solution, I would suggest that we put these new files in a separate folder, not the top level of the repo to make it a bit less cluttered.

**Comment by mattprintz** [comment]
@bgyori I have relocated the testing scripts to a new validation/ dir and it's looking cleaner. Thanks for the suggestion.

**Review by mehalter — APPROVED** [review]
This looks great! Definitely improves the local development and testing of examples and schemas. I went ahead and updated the github actions to also use this script rather than relying on the other GitHub action as well.

**Pull request merged**
