### PR TITLE
feat(petrinet): Add stratification support to AlgebraicPetri integration

### PR DESCRIPTION
**Pull request by mehalter**
This adds an interoperability library for converting an ASKEMNet JSON to a `LabelledPropertyNet` in `AlgebraicPetri` and the ability to convert it back into an ASKEMNet JSON

### CODE REVIEW

**Comment by mehalter** [comment]
This does not currently handle dealing with a typed petri net because the types and the type system are not captured in the model representation and we currently do not have a method of generically adding types to an already constructed petri net. This piece of functionality will need to be discussed. Our current API requires typed petri nets be built out from the type system with wiring diagrams.

**Comment by anandijain** [comment]
I'm not positive, but is the JSONSchema strong enough to lower to `PropertyLabelledReactionNet`? It would be pretty convenient in making the lowering to ODESystem with defaults, custom rates, and observed a bit easier

**Comment by mehalter** [comment]
Converting this to a draft while I implement the creation of typed petri nets now that #28 has been merged in

**Comment by brandomr** [comment]
@mehalter what happens when there are completed semantics (e.g. `ode`) for a model? Will that be propagated through operations like stratification? Could you expand the example to include the semantics so we'd know where get/set initial conditions and parameters?

**Comment by p-stokes** [comment]
> @mehalter what happens when there are completed semantics (e.g. `ode`) for a model? Will that be propagated through operations like stratification? Could you expand the example to include the semantics so we'd know where to get/set initial conditions and parameters?

@brandomr I'm working on this now. We discussed it with @liunelson last week, that stratification will return a span, i.e., the stratified model as the apex with projection maps to the input component models. Any semantics stuff won't be in the apex, but you can map to it in the components.

**Comment by jpfairbanks** [comment]
@p-stokes, I looked into the error message and I think the problem might be that Julia treats dictionaries as different even if they have the same values. 

When we load the Property reaction nets from JSON we get different dictionaries for the type system (even though they have the same content). 

```julia

julia> codom(augmented_sir)[:, :sprop][1] == codom(augmented_flux)[:,:sprop][1]
false

julia> codom(augmented_sir)[:, :sprop][1]
Dict{String, Any} with 3 entries:
  "name"        => "Pop"
  "id"          => "People"
  "description" => "Compartment of individuals in a human population"

julia>  codom(augmented_flux)[:,:sprop][1]
Dict{String, Any} with 3 entries:
  "name"        => "Pop"
  "id"          => "Pop"
  "description" => "Compartment of individuals in a human population"
```

Then in the pullback code hits this error message https://github.com/AlgebraicJulia/Catlab.jl/blob/30999e1e55ea825b5b8eefd15e48f10f4c961b29/src/categorical_algebra/FreeDiagrams.jl#L176. This is why you shouldn't check preconditions, just run the code and hope you don't segfault.

**Comment by jpfairbanks** [comment]
I got past that error with this workaround, but now there is a deeper error.

```julia
augmented_flux′ = LooseACSetTransformation(augmented_flux.components, (Name=x->nothing, Prop=x->nothing), augmented_flux.dom, augmented_sir.codom)
stratified = typed_product(augmented_sir, augmented_flux′)
```

**Comment by liunelson** [comment]
@mehalter @p-stokes @jpfairbanks 
Are there several inter-dependant features being developed in this PR?
1. AMR-to-Petri
2. Petri-to-AMR
3. stratified model containing the mapping back to the base/component models

There is urgent interest for (1) and (2) since their absence is blocking TA3 integration. Could you offer a timeline for a merge?

**Comment by mehalter** [comment]
@liunelson I think we can go ahead and separate out a PR that gets the basic functionality for AlgebriacPetri <-> AMR it just won't have support for stratified models. I will cherry pick commits and make a new PR

**Comment by mehalter** [comment]
I am going to go ahead and close out this PR to decrease confusion on what is going to be merged. I am not going to delete the branch though until the other PR is finished and merged in. For anyone that was using this PR as reference (1) don't use the Julia code here as reference for the integration script API as this is changing and being made a lot simpler (2) if you are using the `sir_flux_span.json` file as a reference for an example stratified AMR this file is also present in the new branch: https://github.com/DARPA-ASKEM/Model-Representations/blob/4c42aa7f5d48df84f87330fc2d6015b0fbcf6c03/petrinet/examples/sir_flux_span.json

**Pull request closed without merging**
